### ISSUE TITLE
About the uncertainty

### ISSUE THREAD

**Issue by LingerWang** [abdo-eldesokey/pncnn#1]
Hi, I appreciate your work very much, but I have question on understanding. I want to know why the uncertainty of y  can be estimated as the cov(y)  in your paper on page 5 left column , formula (7) Thanks!

**Comment by zhouqunbing** [comment]
> Hi, I appreciate your work very much, but I have question on understanding. I want to know why the uncertainty of y can be estimated as the cov(y) in your paper on page 5 left column , formula (7) Thanks!
Can you tell me why?
