### ISSUE TITLE
RuntimeError for model=f.CNN().to(device)

### ISSUE THREAD

**Issue by YanhaoZhang** [abdo-eldesokey/pncnn#2]
Hi, Thanks a lot for releasing the code. It is a very interesting work. I am trying to run it with the default parameters in `workspace/kitti/pncnn`, and got a following error at [this line](https://github.com/abdo-eldesokey/pncnn/blob/c6122e9c442eabeb0145b241121aeba0039eb5e7/main.py#L134) in main function `model=f.CNN().to(device)`. May I ask for any suggestions? Many thanks.
![image](https://user-images.githubusercontent.com/36495922/91539677-05fe3e80-e95d-11ea-999e-ec26e3618648.png)

**Comment by YanhaoZhang** [comment]
I find that setting the gpu to 0 in json file solve this error.

**Comment by anupamsobti** [comment]
One can also use `torch.load(checkpt_path, 'cuda:0')`

**Comment by YanhaoZhang** [comment]
Many thanks @anupamsobti
